/* Screen copy for the intake + delivery kit, in both shipped languages. */
const APP_TEXT = {
  "zh-CN": {
    menu: "菜单", help: "帮助", myApp: "我的申请",
    saveExit: "保存并退出", next: "继续", prev: "上一步", autosaved: "已自动保存，可随时关闭页面",
    sections: [
      { name: "基本信息", state: "done" }, { name: "证件", state: "done" },
      { name: "行程与费用", state: "current" }, { name: "在职与收入", state: "todo" },
      { name: "上传材料", state: "todo" }],
    sectionNow: "行程与费用",
    questions: [
      { id: "purpose", step: 12, kind: "radio",
        question: "你这次去申根国家主要做什么？",
        hint: "选择最接近的一项。后面会根据它决定需要哪些材料，选错了也可以回来改。",
        options: [
          { value: "tour", title: "旅游", hint: "包括探访朋友，但不住在对方家里" },
          { value: "visit", title: "探亲访友", hint: "需要对方出具邀请函，并附上对方的身份或居留证明" },
          { value: "biz", title: "商务出差", hint: "需要对方公司的邀请函，以及你所在公司的派遣函" },
          { value: "study", title: "短期培训或学习", hint: "不超过 90 天的课程、研讨或交流" }],
        footnote: "如果这次行程有多个目的，选择停留时间最长的那一个。" },
      { id: "entry", step: 13, kind: "date",
        question: "你打算哪一天入境申根区？",
        hint: "按你目前的计划填写。还没订机票也没关系，之后可以改。",
        dateHint: "例如 2026 年 09 月 01 日" },
      { id: "passport-no", step: 14, kind: "text",
        question: "你的护照号码是多少？",
        hint: "请与护照资料页完全一致，包括字母大小写。这个号码会自动填进申请表。",
        error: "护照号码需要 9 位，请检查后重新填写" }],
    purposeNote: "这一步只影响材料清单，不会提交给使领馆。",
    sendTitle: "把续填链接发到邮箱？", sendBody: "我们只发这一封，不做营销推送。",
    send: "发送", cancel: "取消", email: "邮箱",
    uploadSection: "上传材料",
    uploadTitle: "还差 3 份材料",
    uploadLede: "每一项都写了为什么需要。可以现在传，也可以先跳过，之后回来补。",
    modeList: "清单", modeDrop: "拖拽上传", modePick: "选择文件", modeCam: "连续拍照",
    items: [
      { id: "u1", title: "护照资料页", rationale: "用来核对姓名拼写与有效期，姓名会自动填进申请表。", state: "done", files: ["passport-page.jpg"] },
      { id: "u2", title: "近三个月银行流水", rationale: "使馆用它判断你能负担这次行程的费用。", state: "redo", detail: "上一份缺少第 3 页，请重新上传完整版。" },
      { id: "u3", title: "在职证明", rationale: "说明你有稳定的工作和回国的理由。我们会提供可编辑模板。", state: "checking" },
      { id: "u4", title: "户口本（全本）", rationale: "用于核对家庭关系，部分使馆要求。", state: "todo" },
      { id: "u5", title: "结婚证", rationale: "只有在配偶随行或作为担保人时才需要。", state: "optional" }],
    dropTitle: "银行流水需要重新上传",
    dropBody: "上一份缺少第 3 页。请上传覆盖最近三个月、页码连续的完整版。",
    camTitle: "拍摄户口本",
    camBody: "一页一张，按顺序拍。拍完可以调整顺序，顺序会影响打印出来的次序。",
    submit: "提交给人工复核",
    packBadge: "已完成人工复核 · 2026-08-08",
    packTitle: "法国短期旅游签证 · 材料包已准备好",
    packLede: "共 14 份文件。先看「打印与递交清单」，按顺序打印即可。还有 1 项需要你确认，见一致性校验。",
    packTrust: [
      { label: "官方来源核对于 2026-08-01", icon: "book-open-text" },
      { label: "42 项一致性校验", icon: "git-compare-arrows" },
      { label: "人工复核 · 李工", icon: "user-check" }],
    packWarnTitle: "有 1 项需要你确认",
    packWarn: "在职证明与社保记录上的入职日期差了两个月。在一致性校验里可以看到具体位置和处理方式。",
    treeHeader: "材料包 · 14 份", downloadAll: "全部下载（ZIP）", downloadShort: "全部下载",
    openTree: "打开材料包目录（14 份）", treeSheet: "材料包目录",
    tabs: [["file", "文件说明"], ["check", "一致性校验"], ["src", "来源与提醒"]],
    checkSummary: "共检查 42 项，1 项需要你确认，1 项建议核对。",
    tree: [
      { id: "s1", name: "从这里开始", children: [
        { id: "f1", name: "打印与递交清单.pdf", kind: "pdf", language: "zh-CN", status: "ready" },
        { id: "f2", name: "面签当天带什么.pdf", kind: "pdf", language: "zh-CN", status: "ready" }] },
      { id: "s2", name: "官方文件", count: 4, children: [
        { id: "f3", name: "申根签证申请表（已填）.pdf", kind: "pdf", language: "fr", status: "ready" },
        { id: "f4", name: "使馆材料清单（原件）.pdf", kind: "pdf", language: "fr", status: "official" },
        { id: "f5", name: "预约确认页.pdf", kind: "pdf", language: "fr", status: "ready" }] },
      { id: "s3", name: "可编辑模板", children: [
        { id: "f6", name: "在职证明（模板）.docx", kind: "doc", language: { code: "zh-CN", name: "中文 / English" }, status: "review" },
        { id: "f7", name: "行程说明（模板）.docx", kind: "doc", language: { code: "zh-CN", name: "中文 / English" }, status: "ready" },
        { id: "f8", name: "费用承担说明（模板）.docx", kind: "doc", language: { code: "zh-CN", name: "中文 / English" }, status: "ready" }] },
      { id: "s4", name: "本人材料", children: [
        { id: "f9", name: "护照资料页.jpg", kind: "img", language: { code: "zh-CN", name: "中文 / English" }, status: "ready" },
        { id: "f10", name: "银行流水.pdf", kind: "pdf", language: "zh-CN", status: "waiting" },
        { id: "f11", name: "户口本（6 页）.pdf", kind: "pdf", language: "zh-CN", status: "ready" }] },
      { id: "s5", name: "来源与提醒", children: [
        { id: "f12", name: "本次材料的官方来源", kind: "link", language: "zh-CN", status: "ready" }] }],
    files: {
      f6: { name: "在职证明（模板）.docx", badge: "人工复核中", badgeTone: "info", pages: 1, updated: "2 小时前更新",
        purpose: "使馆用这份文件确认你有稳定的工作和回国的理由。模板已按你填写的公司名称、职位和入职日期生成，抬头和落款留给公司填。",
        instructions: ["打印在公司抬头纸上，由 HR 或直属主管签字并加盖公章。", "落款日期需在递交前 30 天内。", "如果公司要求先看内容，可以把这份文件直接发给 HR。"] },
      f1: { name: "打印与递交清单.pdf", badge: "先看这份", badgeTone: "success", pages: 2, updated: "刚刚生成",
        purpose: "按递交顺序列出全部 14 份材料，标明哪些要原件、哪些要复印件、哪些需要签字。",
        instructions: ["按清单顺序打印并排好。", "打勾确认每一项都在文件夹里。", "面签当天把这张清单放在最上面。"] },
      f10: { name: "银行流水.pdf", badge: "待你补充", badgeTone: "warning", pages: 0, updated: "缺少第 3 页",
        purpose: "使馆用它判断你能负担这次行程的费用。需要覆盖最近三个月、页码连续。",
        instructions: ["回到「上传材料」重新上传完整版。", "银行盖章的版本更稳妥，但不是必须。"] },
    },
    fallbackFile: { name: "示例文件", purpose: "选择左侧任意一份文件查看说明。", instructions: [] },
    checks: [
      { id: "c1", field: "在职起始日期", severity: "conflict",
        readings: [{ source: "在职证明", value: "2021-03-01" }, { source: "社保记录", value: "2021-05-01" }],
        action: "两处日期不一致。请以社保记录为准，或让公司出具一份更正说明。" },
      { id: "c2", field: "出行城市", severity: "check",
        readings: [{ source: "机票预订", value: "巴黎 CDG" }, { source: "住宿预订", value: "里昂" }],
        action: "行程里没有说明从巴黎去里昂的方式。补一张火车票，或在行程说明里写清楚。" },
      { id: "c3", field: "护照有效期", severity: "pass",
        readings: [{ source: "护照资料页", value: "2031-04-18" }, { source: "计划返程", value: "2026-09-14" }] }],
    sources: [
      { title: "法国驻华使馆 · 短期签证材料清单", publisher: "France-Visas", url: "france-visas.gouv.fr", quote: "银行对账单需覆盖最近三个月。" },
      { title: "申根签证通用要求", publisher: "European Commission", url: "ec.europa.eu" },
      { title: "签证中心预约与递交流程", publisher: "VFS Global", url: "vfsglobal.cn" }],
    caveats: ["最终是否受理与批准由使领馆决定，本服务不代办、不承诺结果。", "官方要求可能随时调整。这份材料包核对于 2026-08-01。"],
  },
  en: {
    menu: "Menu", help: "Help", myApp: "My application",
    saveExit: "Save and exit", next: "Continue", prev: "Previous step", autosaved: "Saved automatically — you can close this page at any time",
    sections: [
      { name: "About you", state: "done" }, { name: "Identity documents", state: "done" },
      { name: "Itinerary and costs", state: "current" }, { name: "Employment and income", state: "todo" },
      { name: "Uploads", state: "todo" }],
    sectionNow: "Itinerary and costs",
    questions: [
      { id: "purpose", step: 12, kind: "radio",
        question: "What is the main purpose of this trip to the Schengen area?",
        hint: "Choose the closest match. This decides which documents you need, and you can come back and change it.",
        options: [
          { value: "tour", title: "Tourism", hint: "Includes visiting friends, as long as you are not staying at their home" },
          { value: "visit", title: "Visiting family or friends", hint: "Needs an invitation letter from them, plus proof of their identity or residence" },
          { value: "biz", title: "Business travel", hint: "Needs an invitation from the host company and a letter from your own employer" },
          { value: "study", title: "Short course or training", hint: "Courses, seminars or exchanges of no more than 90 days" }],
        footnote: "If this trip has more than one purpose, choose the one you will spend the most time on." },
      { id: "entry", step: 13, kind: "date",
        question: "Which day do you plan to enter the Schengen area?",
        hint: "Fill in your current plan. It is fine if you have not booked flights yet — you can change it later.",
        dateHint: "For example 2026 / 09 / 01" },
      { id: "passport-no", step: 14, kind: "text",
        question: "What is your passport number?",
        hint: "It has to match the passport data page exactly, including capital letters. We fill this into the application form for you.",
        error: "A passport number has 9 characters. Please check it and enter it again." }],
    purposeNote: "This answer only affects your document list. It is not sent to the consulate.",
    sendTitle: "Email yourself the link back?", sendBody: "One email, nothing else. We do not send marketing.",
    send: "Send it", cancel: "Not now", email: "Email address",
    uploadSection: "Uploads",
    uploadTitle: "Three documents still to go",
    uploadLede: "Each item says why it is needed. Upload now, or skip and come back to it later.",
    modeList: "Checklist", modeDrop: "Drag and drop", modePick: "Choose files", modeCam: "Photograph pages",
    items: [
      { id: "u1", title: "Passport data page", rationale: "Used to check the spelling of your name and the expiry date. The name is filled into the form for you.", state: "done", files: ["passport-page.jpg"] },
      { id: "u2", title: "Bank statement, last three months", rationale: "The consulate uses it to judge whether you can cover the cost of this trip.", state: "redo", detail: "The last one was missing page 3. Please upload the complete version." },
      { id: "u3", title: "Employment letter", rationale: "Shows that you have steady work and a reason to return. We give you an editable template.", state: "checking" },
      { id: "u4", title: "Household register, all pages", rationale: "Used to check family relationships. Some consulates require it.", state: "todo" },
      { id: "u5", title: "Marriage certificate", rationale: "Only needed if your spouse travels with you or acts as your sponsor.", state: "optional" }],
    dropTitle: "The bank statement needs uploading again",
    dropBody: "The last one was missing page 3. Please upload a complete version covering the last three months with no gaps in the page numbers.",
    camTitle: "Photograph the household register",
    camBody: "One page per photo, in order. You can reorder them afterwards — the order is the order they print in.",
    submit: "Send for human review",
    packBadge: "Human review completed · 2026-08-08",
    packTitle: "French short-stay tourist visa · your pack is ready",
    packLede: "14 documents. Start with the printing and submission checklist and print in that order. One item still needs confirming — see the consistency check.",
    packTrust: [
      { label: "Official sources checked 2026-08-01", icon: "book-open-text" },
      { label: "42 consistency checks", icon: "git-compare-arrows" },
      { label: "Human review · Li", icon: "user-check" }],
    packWarnTitle: "One item needs confirming",
    packWarn: "The employment letter and the social-insurance record give start dates two months apart. The consistency check shows where and what to do about it.",
    treeHeader: "Document pack · 14 files", downloadAll: "Download everything (ZIP)", downloadShort: "Download all",
    openTree: "Open the pack contents (14 files)", treeSheet: "Pack contents",
    tabs: [["file", "About this file"], ["check", "Consistency check"], ["src", "Sources and caveats"]],
    checkSummary: "42 items checked. 1 needs confirming, 1 is worth checking.",
    tree: [
      { id: "s1", name: "Start here", children: [
        { id: "f1", name: "Printing and submission checklist.pdf", kind: "pdf", language: "zh-CN", status: "ready" },
        { id: "f2", name: "What to bring on the day.pdf", kind: "pdf", language: "zh-CN", status: "ready" }] },
      { id: "s2", name: "Official documents", count: 4, children: [
        { id: "f3", name: "Schengen application form (completed).pdf", kind: "pdf", language: "fr", status: "ready" },
        { id: "f4", name: "Consulate document list (original).pdf", kind: "pdf", language: "fr", status: "official" },
        { id: "f5", name: "Appointment confirmation.pdf", kind: "pdf", language: "fr", status: "ready" }] },
      { id: "s3", name: "Editable templates", children: [
        { id: "f6", name: "Employment letter (template).docx", kind: "doc", language: { code: "zh-CN", name: "中文 / English" }, status: "review" },
        { id: "f7", name: "Itinerary statement (template).docx", kind: "doc", language: { code: "zh-CN", name: "中文 / English" }, status: "ready" },
        { id: "f8", name: "Statement of who pays (template).docx", kind: "doc", language: { code: "zh-CN", name: "中文 / English" }, status: "ready" }] },
      { id: "s4", name: "Your own documents", children: [
        { id: "f9", name: "Passport data page.jpg", kind: "img", language: { code: "zh-CN", name: "中文 / English" }, status: "ready" },
        { id: "f10", name: "Bank statement.pdf", kind: "pdf", language: "zh-CN", status: "waiting" },
        { id: "f11", name: "Household register (6 pages).pdf", kind: "pdf", language: "zh-CN", status: "ready" }] },
      { id: "s5", name: "Sources and caveats", children: [
        { id: "f12", name: "Official sources for this pack", kind: "link", language: "zh-CN", status: "ready" }] }],
    files: {
      f6: { name: "Employment letter (template).docx", badge: "In human review", badgeTone: "info", pages: 1, updated: "updated 2 hours ago",
        purpose: "The consulate uses this to confirm that you have steady work and a reason to come back. The template already carries the employer, job title and start date you gave us; the letterhead and signature are for your company to add.",
        instructions: ["Print it on company letterhead and have HR or your line manager sign and stamp it.", "The date on it must be within 30 days of your submission.", "If your company wants to see the wording first, send them this file as it is."] },
      f1: { name: "Printing and submission checklist.pdf", badge: "Read this first", badgeTone: "success", pages: 2, updated: "generated just now",
        purpose: "Lists all 14 documents in submission order, and marks which need to be originals, which are copies, and which need a signature.",
        instructions: ["Print and arrange the documents in the order on the checklist.", "Tick each line once it is in the folder.", "Keep this checklist on top on the day of your appointment."] },
      f10: { name: "Bank statement.pdf", badge: "Waiting on you", badgeTone: "warning", pages: 0, updated: "page 3 missing",
        purpose: "The consulate uses it to judge whether you can cover the cost of the trip. It has to cover the last three months with no gaps in the page numbers.",
        instructions: ["Go back to Uploads and upload the complete version.", "A version stamped by the bank is safer, but it is not required."] },
    },
    fallbackFile: { name: "Example file", purpose: "Choose any file on the left to see what it is for.", instructions: [] },
    checks: [
      { id: "c1", field: "Employment start date", severity: "conflict",
        readings: [{ source: "Employment letter", value: "2021-03-01" }, { source: "Social insurance record", value: "2021-05-01" }],
        action: "The two dates disagree. Use the social-insurance date, or ask your employer for a short correction letter." },
      { id: "c2", field: "Destination city", severity: "check",
        readings: [{ source: "Flight booking", value: "Paris CDG" }, { source: "Accommodation", value: "Lyon" }],
        action: "Your itinerary does not say how you travel from Paris to Lyon. Add a train ticket, or explain it in the itinerary statement." },
      { id: "c3", field: "Passport validity", severity: "pass",
        readings: [{ source: "Passport data page", value: "2031-04-18" }, { source: "Planned return", value: "2026-09-14" }] }],
    sources: [
      { title: "French Embassy in China · short-stay document list", publisher: "France-Visas", url: "france-visas.gouv.fr", quote: "Bank statements must cover the last three months." },
      { title: "General Schengen visa requirements", publisher: "European Commission", url: "ec.europa.eu" },
      { title: "Appointment and submission process", publisher: "VFS Global", url: "vfsglobal.cn" }],
    caveats: ["The consulate decides whether to accept and approve your application. We are not an agency and promise no outcome.", "Official requirements can change. This pack was checked on 2026-08-01."],
  },
};

Object.assign(window, { APP_TEXT });
